name: goblintAnalysisNoSubDir

on:
  push:
  pull_request:

jobs:
  generate-Sarif:
    env:
      # ./analysisTarget/main.c needs to be replaced with ./analysisTarget/PATH_TO_MAIN
      #the prefix  ./analysisTarget/ is removed in Goblint, so the location shows correctly in Github
      MAIN_NAME: './testCRepo/05-inf_loop.c'
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.0 # matches opam lock file
          # don't add any other because they won't be used

    runs-on: ${{ matrix.os }}
    permissions:
       security-events: write
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Checkout Goblint repository
         uses: actions/checkout@v2
         with:
           path: analyzer
           repository: AlexanderEichler/analyzer
           #this path needs to be changed to the main branch
           ref: integrationSarif
       
