name: goblintAnalysisNoSubDir

on:
  push:
  pull_request:

jobs:
  generate-Sarif:
    env:
      # ./analysisTarget/main.c needs to be replaced with ./analysisTarget/PATH_TO_MAIN
      #the prefix  ./analysisTarget/ is removed in Goblint, so the location shows correctly in Github
      MAIN_NAME: './testCRepo/05-inf_loop.c'
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.0 # matches opam lock file
          # don't add any other because they won't be used

    runs-on: ${{ matrix.os }}
    permissions:
       security-events: write
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Checkout Goblint repository
         uses: actions/checkout@v2
         with:
           path: analyzer
           repository: AlexanderEichler/analyzer
           #this path needs to be changed to the main branch
           ref: integrationSarif

        - name: Set up OCaml ${{ matrix.ocaml-compiler }}
          env:
            # otherwise setup-ocaml pins non-locked dependencies
            # https://github.com/ocaml/setup-ocaml/issues/166
            OPAMLOCKED: locked
          uses: ocaml/setup-ocaml@v2
          with:
            ocaml-compiler: ${{ matrix.ocaml-compiler }}
            path: analyzer
        - name: Install dependencies
          working-directory: analyzer
          run: |
            eval $(opam env)
            pwd
            ls
            opam install . --deps-only --locked
            eval $(opam env)
        - name: Build
          working-directory: analyzer
          run: |
            pwd
            ./make.sh nat
            ./goblint

        - name: Generate the Sarif output
          run:  |
            pwd
            ls
            ./analyzer/goblint --sarif -o GitHubSarif.sarif  ${{env.MAIN_NAME}}
        - name: Upload the generated Sarif File
          uses: github/codeql-action/upload-sarif@v1
          with:
             # Path to SARIF file relative to the root of the repository
            sarif_file: GitHubSarif.sarif
