name: uploadSarif

on:
  push:
  pull_request:

jobs:
  generate-Sarif:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.0 # matches opam lock file
          # don't add any other because they won't be used

    runs-on: ${{ matrix.os }}
    permissions:
       security-events: write
    steps:
        - name: Checkout Goblint repository
          uses: actions/checkout@v2
          with:
              repository: AlexanderEichler/analyzer
              ref: SarifFormatV2
              path: goblint
        - name: PWD
          run: pwd
        - name: Set up OCaml ${{ matrix.ocaml-compiler }}
          env:
            # otherwise setup-ocaml pins non-locked dependencies
            # https://github.com/ocaml/setup-ocaml/issues/166
            OPAMLOCKED: locked
          uses: ocaml/setup-ocaml@v2
          with:
            ocaml-compiler: ${{ matrix.ocaml-compiler }}
            working-directory: ./goblint
        - name: PWD
          run: pwd
        - name: Install dependencies
          run: |
            pwd
            cd ..
            cd goblint
            pwd
            opam install . --deps-only --locked
          working-directory: ./goblint
        - name: Build
          run: ./make.sh nat
          working-directory: ./goblint
         - name: Checkout code
          uses: actions/checkout@v2
          with:
              path: analysisTarget
        - name: Generate the Sarif output
          run: ./goblint --sarif -o GitHubSarif.sarif /home/runner/work/testCRepo/testCRepo/main.c
          #working-directory: ./goblint
        - name: Upload the generated Sarif File
          uses: github/codeql-action/upload-sarif@v1
          with:
             # Path to SARIF file relative to the root of the repository
            sarif_file: GitHubSarif.sarif
